name: Build Package
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Import PAT from Actions secrets
        run: |
         cd SwiftPamphletApp
         sed -i '' s/'gitHubAccessToken = ""'/'gitHubAccessToken = "${{ secrets.PAT }}"'/ SwiftPamphletAppConfig.swift
         cd ..
      - name: Build
        run: |
          if grep -q 'gitHubAccessToken = ""' ./SwiftPamphletApp/SwiftPamphletAppConfig.swift ; then
            echo "please setup your personal access token to Actions secrets and name it to PAT" && exit
          fi
          chmod +x ./compile.command
          /bin/bash -c ./compile.command
          zip -r9 戴铭的开发小册子.zip 戴铭的开发小册子.app
      - name: Upload App.zip
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "戴铭的开发小册子.zip"
          path: "戴铭的开发小册子.zip"
